[tool.poetry]
name = "demo"
version = "0.1.0"
description = ""
authors = ["Ma Lu <luma26c@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
stable-baselines3 = "2.3.2"
torch = "2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

